### ISSUE TITLE
University of California Libraries: Research Data Matters

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#11]
Information about registered data management training resource

- [ ] Date resource added: 08/24/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL:  http://dmtclearinghouse.esipfed.org/node/10172

**Comment by njhoebel** [comment]
1.  Added names of researchers to the description.
2.  Changed the name of the authoring organization to include the "University of California Libraries"
3.  Put the names of the two people mentioned as Contributors of type "Project Administration and Management" rather than authors as that was their role per the home page.  (We don't necessarily need people's names as authors if there is only reference to an organization.)
