### ISSUE TITLE
Library Carpentry OpenRefine

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#130]
Information about registered data management training resource

- [ ] Date resource added: 11/15/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10270

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added license: CC-BY 4.0 
added keywords: OpenRefine
added citation: Erin Carillo (Ed.), Owen Stephens (Ed.), Juliane Schneider (Ed.), Paul R. Pival (Ed.), Kristin Lee (Ed.), Carmi Cronje (Ed.), James Baker, Christopher Erdmann, Tim Dennis, mhidas, Daniel Bangert, Evan Williamson, … Jeffrey Oliver. (2019, July). LibraryCarpentry/lc-open-refine: Library Carpentry: OpenRefine, June 2019 (Version v2019.06.1). Zenodo. http://doi.org/10.5281/zenodo.3266144

added ID: 10.5281/zenodo.3266144
added type: DOI

added version: Version v2019.06.1

added learning resource type: Lesson

**Comment by njhoebel** [comment]
1.  Removed the author names to Contributor of type Editor since that is what the citation says and the resource itself on github.  Also added the other editor names.
2.  Retained the Authoring Organization to be Library Carpentry.  It's possible to have only an authoring organization without author names, and vice versa for this section.
3.  Added a few keywords:  Data transformation, and Metadata.
4.  Added a published date.
5.  Added Data professional and Data manager to the Target audience field.  
Move to publish.
