### ISSUE TITLE
The Realities of Research Data Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#148]
Information about registered data management training resource

- [ ] Date resource added: 01/15/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10303

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
- Changed the description to make it a collection by listing all the components of the resource including the URLs to each component and the DOIs in this case.
- Also made the Media type a collection since it is a 4 part series of reports plus supplemental materials including a webinar.  
- Added collaborator organizations that were mentioned in the overview.
- Good example of a collection & how to treat, hence the edge case lable.
