### ISSUE TITLE
Hands-on Intro to SQL (Structured Query Language)

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#17]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10166

**Comment by njhoebel** [comment]
1.  Added some description about the dataset used to give people an idea of the context for this workshop and to distinguish it from others that we might find.
2.  Changed the name of the authoring organization & publisher to be "Stanford University" rather than "Stanford".  Also, because I knew this person and knew where she works I used "Stanford University Libraries" rather than just Stanford University.  No way you would have known that, probably, as I couldn't see it described on the course itself, and Stanford University would have been just fine too in the absence of that knowledge.
3.  Added subject discipline for "Physical Sciences:  Environmental Science" because of the dataset used.
