### ISSUE TITLE
Coffee and Code: NoSQL

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#172]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10329

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Reviewed by Raisa.
The changes I made to this record are:
1.  Adding the UNM RDS as a Contributor since this instance of the Coffee & Code workshop series is made available by that organization.  Type = Organizer
2.  Changed the publisher to UNM RDS.
3. Changed the Learning Resource type to Learning Activity from Course.
