### ISSUE TITLE
Coffee and Code: Reproducibility and Communication

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#174]
Information about registered data management training resource

- [ ] Date resource added: 01/31/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10331

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
RAisa reviewed as well.
I made the following changes to the record:
1.  Corrected Title ("Reproducibility" rather than "Reproducability"
2. Found more info on the ,ipynb page in the repo, as follows:
a.  Added Jonathon Wheeler as an author
b.  Added more descriptive information about what was covered in the workshop
c.  Added keywords related to data re-use and electronic notebooks
d.  Added the FAIR Data Principles Framework with node of Re-usable data since that was explicitly mentioned in the description.
e.  Changed the Learning Resource Type to Learning Activity since there are activities associated with this resource that will involve using tools in a playground.
