### ISSUE TITLE
U.S. Fish and Wildlife Geospatial Services

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#18]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10165

**Comment by jwikle** [comment]
This one may not meet the criteria.

**Comment by njhoebel** [comment]
1.  Changed this record to point to the US FWS training "catalog" that has a search interface on top as a kind of "collection level" record.  
2.  Kept the "service" media type, but changed the learning resource type to "Course".
3.  Changed the description, but included the link to the datasets page that you found as that's a good one too even though as you suspected, it probably wouldn't have fit the criteria by itself.  
4.  Changed the organization name to be "U.S. Fish and Wildlife Service" rather than "USFWS" to help non-US folks.  
5.  Kept the "no fee" access even though some are available for a cost, but mentioned that in the description.
6.  Added two subject disciplines (probably doesn't adequately cover the subjects, but probably enough for the high level):  Physical Sciences:  Earth Sciences and Environmental Sciences.  
7.  Besides the Federal agency... keyword / phrase, added the good ol" "Data management planning" KW / phrase as well.  
Nice resource;  glad we could use it in this way.  Let me know if you have questions about this...
