### ISSUE TITLE
Project Open Data

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#212]
Information about registered data management training resource

- [ ] Date resource added: 03/21/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10375

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
This resource is neither learning nor training. This is just a description of the Project Open Data.
I think, it is worth keeping in the clearinghouse

**Comment by njhoebel** [comment]
I agree that this is a very useful resource.  
1.  Have changed the descriptive information to be less of an advertisement from the page itself, and more descriptive of what topics & key resources are included. 
2.  Have added more keywords for data sharing and data policy.
3.  Have added data policymakers to the target audience.
4.  Changed the authoring organization to be:  CIO Council rather than US Government.
5.  Moved to Publish
