### ISSUE TITLE
Train the Trainer Workshop: How do I create a course in research data management?

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#213]
Information about registered data management training resource

- [ ] Date resource added: 04/04/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10378

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Changed the keywords to represent the focus on education of RDM experts (capacity building, data skills education, data literacy, data lifecycle).
2.  Changed media type to Collection since exercises are included with the presentation slides.
3.  Added the International Digital Curation Conference as a contributor of type:  organizer.
4.  Added the FAIR Data Principles framework as they are explicitly mentioned in the slides.  Did not add specific nodes as the discussion of the principles seemed to be more generic than specifically about each of the principles.
5.  Added the DOI info.
