### ISSUE TITLE
The what, why, when, how, where and who of geological data management 

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#22]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10155

**Comment by jwikle** [comment]
Link is to a static page with a research paper, so it might a well be removed.

**Comment by njhoebel** [comment]
I agree that this resource won't fit within the Clearinghouse per the Selection Criteria now, but rather than delete, I'm going to move it to the Review - Do Not Publish column as it appears to be an excellent resource and we might figure out a way to make these resources known -- as part of a pathfinder or customized list of resources?  Anyway, good find.
