### ISSUE TITLE
Workshop: Research Data Management in a Nutshell

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#233]
Information about registered data management training resource

- [ ] Date resource added: 05/07/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10402

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added keywords
added Citable Locator
added Citable Locator Type: DOI
added Version
added purpose: Professional Development
added Time to Complete: up to 1 hour
added Media Type: Presentation
added Learning Resource Type: Learning Activity

**Comment by njhoebel** [comment]
Looks like a great resource.
- All additions look good although I changed the version number as it appeared to be only version 1 (not 1.1 -- was confusing because the doi number starting with "10" was right next to the version number).  Our practice has been to not include the version number if it is version 1.  
- One other change was to change the order of authors to match the citation order.  Note:  if a new person is created using the add an author tab, the first one entered will be the last one on the list.  Annoying, but true.  So, the last person on the list of authors needs to be entered first when using that button so that it appears last on the list of authors. 
Moved to publish.
