### ISSUE TITLE
Data Management for the Humanities

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#243]
Information about registered data management training resource

- [ ] Date resource added: 10/18/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10432

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
While this is a more or less static set of web pages, there is a lot of good information on it which would be helpful for data curators and undergrads / grads especially.   So, will publish, but add the edge case label.  
Made the following changes:
1.  Removed the Contributor as the one included (DH Curation Guide) is not an organization and there is not really a Type of contributor that matches what the publisher of the DH Curation Guide (i.e., the UK Data Archive) would be to this resource.  There is mention of the adaptation done within the description which provides some attribution.
2.  Changed the Purpose to be "Professional Development" (as there were not downloadable instructions as far as I could see).
3.  Changed the time to be more than 1 hour, but less than a day.
4.  Changed the Media type to be "text" as it's mostly a web page.
5.  Changed the Learning Resource Type to be "Course" because of the range of topics included in the guide.
