### ISSUE TITLE
Open Source Software for Preprocessing GIS Data for Hydrological Models

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#245]
Information about registered data management training resource

- [ ] Date resource added: 10/18/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10434

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Changed the descriptive text a bit to note that other courses, video tutorials and webinars were available from this website.
Added keywords for hydrological data and data modeling.
Changed the media type to Collection since there were a number of different types of resources available.
Changed the learning resource type to Course.
NIce find!
