### ISSUE TITLE
JavaScript Tutorial

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#277]
Information about registered data management training resource

- [ ] Date resource added: 10/30/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10468

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
I am wondering this kind of tutorial is useful for DMTC material?

**Comment by njhoebel** [comment]
This looks like another good resource given the prevalence of JavaScript in working with research data.  I have made the following changes to the record:
1.  Added keywords for data coding and data skills education.
2.  Added last updated information to Version field.
3.  Changed Media Type to "Moving image".
4.  Changed Purpose to "instruction".
5.  Changed Learning Resource Type to Course.
6.  Changed time to "more than 1 day, but less than a week  due to the number of videos to complete the course.
