### ISSUE TITLE
C++ Programming Tutorial Series

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#278]
Information about registered data management training resource

- [ ] Date resource added: 10/30/2109
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10469

Tracking: @karlbenedict @njhoebel

**Comment by zohrehMehrabi** [comment]
I am wondering this kind of tutorial is useful for DMTC material?

**Comment by njhoebel** [comment]
Yes, this looks to be a good series, especially since this method of programming seems to be widely used for data work even though data management is not explicitly mentioned in any of the tutorials.
Made the following changes:
1.  Added more description about what was included in the series.
2.  Added keywords for "data coding" and "data skillbuilding".
3.  Added last updated information to the Version field.
4.  Changed Media type to "moving image" as these are videos with sound included as well as slides (that don't appear to be downloadable).  
5.  Changed purpose to "instruction".
6.  Changed learning resource type to "Course".
7.  Changed intended time to complete to "More than 1 day, but less than a week" because the total series was 10 hours figuring a day = 8 hours.
