### ISSUE TITLE
ESRI Training 

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#36]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10123

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Changes the title of this a bit to take people directly to the Data Management topic area for the ESRI courses.
2.  Added more description about the types of educational resources that are available from ESRI, and the fact that some are free, and some are available for a fee.
3.  Added ESRI as the Publisher.
4. Added subject disciplines for Physical Sciences:  Earth Sciences and for Environmental Sciences.
5.  Added a keyword for "capacity building" -- a more general term for skill building that is being used more frequently.
6.  Changed the Media Type to "Collection" since there are so many options from this main link.
Moved to publish.  Glad to get these in the Clearinghouse!
