### ISSUE TITLE
Introduction to SAGA GIS Software

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#37]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10122

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Added a bit more descriptive information to the description from the first couple of slides in the description.
2.  Added the names of the slide creators (the basis of the video) to the Creator field.
3.  Added keyword for data management planning tools.
4.  Added subject disciplines for Earth Sciences & Environmental Sciences.
5.  Changed the Media Type to Presentation as that's where we've been putting video recorded slide presentations.
6.  Changed the Learning Resource Type to Demo/ Simulation as that appears to be what they are really doing.  
Moved to publish.  This has gotten good reviews looks like, so that's good!
