### ISSUE TITLE
Training Materials for Data Management in Reclamation

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#39]
Information about registered data management training resource

- [ ] Date resource added: 08/30/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10112

Tracking: @karlbenedict @njhoebel

**Comment by jwikle** [comment]
The link to the page downloads a PDF.

**Comment by njhoebel** [comment]
This is a very interesting edge case from the POV of the selection criteria.  While it is a downloadable text which we would  normally not include, it is designed to be used with some of the USGS training modules which are downloadable.  Given the content, and the specific information about the Bureau of Reclamation's focus, I think this is a resource that could be included.  I will publish, but will also include this as an example of an edge case that may help us refine our Selection Criteria.  To publish, I've done the following to the record:
1.  Added more information to the description that referenced the USGS education modules;
2.  Changed the organization name to include "U.S." to follow the naming standards we've been using (could be more than one Bureau of Reclamation around the world..."
3.  Added keywords related to data management planning, data life cycle, metadata, and added a new keyword for "Metadata editors";
4.  Added subject disciplines for Physical Sciences:  Earth Sciences, and for Physical Sciences:  Environmental Sciences;
5.  Because the materials supplement the USGS modules I have added them to that Educational Framework and added the steps for Plan and Metadata/Describe.
