### ISSUE TITLE
Digital Curation 101 Materials

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#5]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10178

**Comment by njhoebel** [comment]
Made the following changes:
1.  Added context in the description which noted that these materials are actually curricula guidelines (wasn't obvious to me from the description on the landing page until I scrolled around a bit) which makes them more than a static web page that would probably be used as a reference on a pathfinder.  We have not been including these kinds of resources in the DMTC to date per our selection criteria.
2.  Also added some context about the DCC curation lifecycle model too as that is the way the resources are organized.  
3. Added keyword for "data curation" since that was one added since you created the record.
4.  Changed the media type to "Collection" since there are a (vast!) number of resources listed and available from here.
5.  Changed the Purpose to "Professional Development" since the target audience seemed largely to be either self-educators or data professionals whose responsibility it is to teach about RDM.
6. Changed Learning Resource Type to "Educator Curriculum Guide".  
Nice set of resources;  good catch!
