### ISSUE TITLE
STL Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#537]
Information about registered data management training resource

- [ ] Date resource added: 8/12/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10861

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added keywords for "3 D modeling" and "Spatial Capture-Recapture modeling".
Added "librarian" to target audience.
Changed contribution of Jennifer Moore to "Conceptualization" rather than "Other".  Not an exact term, but maybe more descriptive than "other".  May have to consider adding that one, but we'll see how often it's used.
