### ISSUE TITLE
Confocal Microscopy Data Curation Primer

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#541]
Information about registered data management training resource

- [ ] Date resource added: 8/13/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10867

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
- Added a brief definition to the description (as I didn't know what confocal microscopy was!), and also the primary fields in which the data visualization technique is used.  
- Added subject discipline fields for the primary fields in which the technique is used.
- Took "undergraduate student" out of the list of target audience, but added "data professional"
- Added "Mentoring" to the contributor type controlled vocabulary list for use instead of "other".  Went back to a few of the primers to add that instead of "other" when it applied.
Moved to publish.
