### ISSUE TITLE
Utiliser le UN Biodiversity Lab pour soutenir les objectifs nationaux de conservation et de développement durable

### ISSUE THREAD

**Issue by zohrehMehrabi** [imls-dmt/resources-workflow#568]
Information about registered data management training resource

- [ ] Date resource added: 9/17/2020
- [ ] Registered by: 
- [ ] Clearinghouse URL: https://dmtclearinghouse.esipfed.org/node/10949

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Added Brock Blevins as contact person.
Added keywords for ABTs, and remote sensing.
Would you please add the French names for the key contributors:  (will have to look at the English version for the full name rather than the acronyms if this is unclear):  GEF, CBD, UNEP and UNDP (which I see you've already done)?  Each contributor would be a Collaborator with the exception of the GEF which is for Funding and Sponsorship.  Let me know if you have questions.  THANK YOU!!!!

**Comment by zohrehMehrabi** [comment]
sure, I'll do it.

**Comment by zohrehMehrabi** [comment]
added the French form of organizations.
