### ISSUE TITLE
Data Management Guidelines

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#57]
Information about registered data management training resource

- [ ] Date resource added: 09/10/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10192

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
Broadened the record for this series of resources as follows:
1.  Changed the title to Data Management Guidelines and the URL to the home page for these resources.
2.  Changed the description to reflect the chapters available from the broader page.
3.  Added license information available from the home page.
4.  Added key words related to the more specific topics.
5.  Changed the purpose to instruction from professional development (since they were guidelines coming from the national repository of record for this type of data.
