### ISSUE TITLE
Metacat: Metadata and Data

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#67]
Information about registered data management training resource

- [ ] Date resource added: 09/13/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10202

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
This is a somewhat marginal resource, but due to the extensive coverage and instructions contained within it (as an administrator's guide), is worth adding.  
Have made the following changes to the record:
1.  Changed the title to:  Metacat Administrator's Guide to match the URL included.
2.  Added information about what is covered in the chapters of the guide.
3.  Added keywords related to metadata, expert guidance, and cyberinfrastructure for science
4.  Added subject disciplines for Earth and Environmental Sciences
5.  Changed publisher to the Regents of the University of California (for the guide itself)
6.  Changed the publication date to reflect the copyright on the web page (2012).
7.  Added software engineer to the target audience.
8.  Added "primary source" to the learning resource type.
9.  Changed the intended time to complete to more than an hour, less than a day.
