### ISSUE TITLE
Data Management Basics and Best Practices

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#69]
Information about registered data management training resource

- [ ] Date resource added: 09/17/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10204

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
added terms: big data, data life cycle
added purpose: instruction
added media type: presentation
added learning resource type: lesson

**Comment by raisaionin** [comment]
Right now, in the clearinghouse it states  that the license is "Standard youtube license"
The resource itself, https://www.youtube.com/watch?v=ir6t9xE9lrc, states  "Creative Commons Attribution license (reuse allowed)
Is this correct?

**Comment by njhoebel** [comment]
Good question:  if there is no other license information available, we've been just usingthe "Standard YouTube license", but as you noticed, UKy Libraries has added a different license designation, so we should add that one.  They don't have a version number on the license, so I just added the CC By Generic 2.0 license.  We can always change if someone raises the issue.  Make sense?

Only change I made was to add the presenter / author's name to the record.  Otherwise, looks good.
Moved to publish.
