### ISSUE TITLE
Data Warehouse Tutorial For Beginners

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#70]
Information about registered data management training resource

- [ ] Date resource added: 09/17/2018
- [ ] Registered by: jawikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10205

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Reviewed, looks good.

**Comment by njhoebel** [comment]
Added  target audiences for data professional and graduate student.
Changed learning resource type to "lesson" rather than learning activity as this tutorial seems to be mostly presentation slides with the consumer of the tutorial not engaging in any activity other than looking a the slides.
Added keywords for "business intelligence" and "data analysis".
Moved to publish.
