### ISSUE TITLE
Introduction to Computer Science and Programming in Python

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#76]
Information about registered data management training resource

- [ ] Date resource added: 09/20/2018 
- [ ] Registered by:  jwikle 
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10212

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
-added to Contact:  Ana Bell (3777), John  Guttag (3779), Eric Grimson (3778). They are listed as instructors. 
-removed from Subject Discipline: Social and Behavior Sciences
-added a keyword to Taxonomy: Computer science
-added "Computer science" to Keywords and short phrases field.
-added Citation to the field
-added to Description: 
"MITx offers a free version of this subject on edX. Please register to get started:

6.00.1x Introduction to Computer Science and Programming Using Python (Started January 22, 2019) help icon
6.00.2x Introduction to Computational Thinking and Data Science (Started March 26, 2019)"

-deleted from Published / Broadcast - 01/01/2016. I did not find the date of publications. So the dates are now blank

-changed time to complete from "more than an hour but less than 1 day" to "more than 1 week"
-changed Learning Resource type from "lesson" to "Course"

**Comment by njhoebel** [comment]
- Also added to description including course features.
- Corrected the license to be CC BY-NC-SA 4.0
- Put publication date back in since it's our policy to put in dates when the resource was broadcast (fall 2016) with either 1/1/YYYY if no other information is given or as this one said that it was broadcast in fall 2016, I added the data 9/1/2016).  
Moved to publish.
