### ISSUE TITLE
Research Rigor & Reproducibility: Understanding the Data Lifecycle for Research Success

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#8]
Information about registered data management training resource

- [ ] Date resource added: 08/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10175

**Comment by njhoebel** [comment]
Excellent resource!
1. I've added more descriptive information including putting this course w/in the context of the larger Best Practices course which is already in the DMTC.  Also added info about what is included in the course, e.g., video lectures, presentation slides, etc.  Info was on the home page for the resource on the Canvas website.
2.  Changed the authoring organization to "Harvard Medical School", but didn't add any author names since I couldn't find (easily) who had created them.  This course appears to be (?) a subset of an earlier module of the Best Practices course, but not evident whether the people are the same at the Harvard Med School, so left that off.
3.  Added keywords for the FAIR data principles for reuse and interoperable data.
4.  Added librarian to target audience.
5.  Added time to complete to be more than 1 day, but less than a week (just guessing here, but makes sense given all the modules and potential activities.)
6.  Made the Media Type a "Collection" since there were all those options for learning as mentioned in #1 above.
7  Made the learning resource type a "unit" rather than a course as it's part of the larger Biomedical  Practices course.
8.  Also added Mediciine & Health Sciences and Medicine and Health Sciences:  Biomedical Science to the subject discipline list, and deleted the Physical Sciences and Mathematics:  Chemistry as I couldn't find evidence that was being addressed.  If you saw it mentioned somewhere, Jacob, please go back and add.
