### ISSUE TITLE
Principles of Database Management

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#83]
Information about registered data management training resource

- [ ] Date resource added: 09/24/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10219

Tracking: @karlbenedict @njhoebel

**Comment by njhoebel** [comment]
1.  Changed this link to a single lecture of a web lecture series to a record for all of them.
2.  Added descriptive language that described the overall series rather than just this lecture.
3.  Added keywords for database models and database design.
4.  Added last modified date to the Version field.  
5.  Moved to publish.
