### ISSUE TITLE
Data Carpentry Ecology Workshop

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#90]
Information about registered data management training resource

- [ ] Date resource added: Updated 09/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10103

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
1. I don't see Tracy Teal as Authoring Person Name. Her name is mentioned in the official citation proved at the website: https://github.com/datacarpentry/ecology-workshop/blob/gh-pages/CITATION
Was surprised that I was not able to find it on the workshop's main page
2. Date created is "04/01/2018", did not find it in the resource

Added keywords: Data Cleaning; Python; R (first added it to the taxonomy); OpenRefine (first added it to the taxonomy); SQL; Spreadsheets  (first added it to the taxonomy)

Added License: CC BY 4.0 license.

Purpose: Instruction
 Time to complete: more than 1 day, less than 1 week
Media type  -  Interactive resource

Learning resource type  - Learning Activity

**Comment by njhoebel** [comment]
1. Re:  questions:  Because that info is in the suggested citation, makes sense to keep it in the record.
2. Changed the date to 4/1/2017 as it appeared in the citation and moved it from date created to date published.
3.  Added subject discipline tags for Earth & Environmental Sciences since it's an "ecology" workshop.  Seemed the closest.
4.  Added target audience tags for data professional and librarian. 
Moved to publish.
