### ISSUE TITLE
Learn Python the Hard Way

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#93]
Information about registered data management training resource

- [ ] Date resource added: 09/27/2018
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10228

Tracking: @karlbenedict @njhoebel

**Comment by raisaionin** [comment]
Added citation, Chicago style

**Comment by raisaionin** [comment]
The resource is definitely worth including into the DMTC, but it is unclear whether we need to include the website that point to the book, https://learnpythonthehardway.org/, or the book itself from Amazon, for example:https://www.amazon.com/gp/product/0134692888/ref=as_li_qf_sp_asin_il_tl?ie=UTF8&tag=lepythhawa-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=0134692888&linkId=9584c3f39e972b770bd16b38594294cf

**Comment by raisaionin** [comment]
added: 1st edition
added: 01/01/2017 for the publication date
added Purpose: Instruction
added Intended time to complete - more than 1 week
added Media Type: Physical object, considering we are describing a book and not the website that refers to this book
added Learning Resource Type: Textbook. considering we are describing a book and not the website that refers to this book

**Comment by njhoebel** [comment]
This is an interesting case.   Would be interesting to get some reviews of this book;  not sure why you thought it should be included, Raisa.  Have you read it / gone through the book?

I did make some changes, as follows:
1.  As this was self-described as "newly updated", I don't think we can call this a first edition, so have deleted that from the version field.
2.  Changed the year of publication to 2016 since that was the copyright date on the web page for the book.
3.  Changed media type to text as physical object would be used for something like a specimen or some other physical object that could be used as part of a learning activity, for example.
4.  Added keywords:  data coding
5.  Changed publisher to represent the form on the web page.  
6.  Will not move this to publish until we have more discussion about whether to include these kinds of self-published books.  There are pro & con reviews on Amazon, but needs discussion by editorial group.
